### ISSUE TITLE
Debian/Ubuntu issue with script/signify_prehash.sh and workaround

### ISSUE THREAD

**Issue by refragable** [Peter-Easton/GrapheneOS-Knowledge#1]
I was building GrapheneOS on Ubuntu 20.04 and at the last step ["Generating signed factory images and full update packages"](https://grapheneos.org/build#generating-signed-factory-images-and-full-update-packages) I got the following error:

`script/signify_prehash.sh: line 13: signify: command not found`

Daniel already made a note of this `signify` issue for Debian/Ubuntu in the [install guide](https://grapheneos.org/install#obtaining-signify) but it's not documented in the official build guide (since he probably uses Arch for everything).

My workaround was to make a symlink:  
```sh
me@server:~/android/grapheneos-10$ type signify-openbsd
signify-openbsd is hashed (/usr/bin/signify-openbsd)
me@server:~/android/grapheneos-10$ ln -s /usr/bin/signify-openbsd ~/bin/signify
me@server:~/android/grapheneos-10$ type signify
signify is /home/user/bin/signify
```
Running `script/release.sh <device>` was successful after the workaround was applied.

**Comment by Peter-Easton** [comment]
Whoops, I should've gotten around to this earlier, that's good to know!

**Comment by Peter-Easton** [comment]
Whoa, whoops. Didn't realize I'd left this open.
