### ISSUE TITLE
Is the info regarding Google camera still up-to-date?

### ISSUE THREAD

**Issue by codethief** [Peter-Easton/GrapheneOS-Knowledge#13]
Google Camera is [listed as broken](https://github.com/Peter-Easton/GrapheneOS-Knowledge/blob/master/App%20Compatibilty%20List/Broken.md) but according to [the GrapheneOS website](https://grapheneos.org/usage#camera) this might have changed recently(?)

> Google Camera can be used with the sandboxed Play services compatibility layer and can take full advantage of the available cameras and image processing hardware as it can on the stock OS.

**Comment by ghost** [comment]
Google Camera fully works now with the Sandboxed Play Services.

**Comment by Peter-Easton** [comment]
https://github.com/Peter-Easton/GrapheneOS-Knowledge/commit/f1a5b14937807ed71d24f24de9460f5afc3a7c07#diff-c4752fc4db9ec2729afc7bd5b12da14683c27cfec700ee99e7bb9b16db1f1fc5

Sorry about that. I'm changing the way I'll enumerate apps that don't work on GrapheneOS.
