### ISSUE TITLE
grouping for App Compatibility List

### ISSUE THREAD

**Issue by b3K1ndRw1nd** [Peter-Easton/GrapheneOS-Knowledge#7]
I wanted to suggest that for the list, it be grouped by app categories, rather than alphabetically?

so, you would have one category like

# Messaging Services
- Element
- Signal Private Messenger
- Telegram
- Telegram FOSS
- WhatsApp Messenger
- Wire (Cannot connect to the server on boot. In order to display notifications you must manually open the app first.)

Would make more in my opinion cause then someone going through the list of a specific services doesn't have to guess which apps do what.

**Comment by Peter-Easton** [comment]
Ahoy!

Someone suggested I put them into a comma separated value chart, so it would be easier to sort using a spreadsheet program. I haven't had much time to work on it yet, but what would you say to that?

**Comment by b3K1ndRw1nd** [comment]
hmm, I see positives and negative in that that really (imo) depend on you and how you want people to interact with the repo,

on one hands, csvs are great and certainly allow for flexibility and functionality.

on the other hand

- I dont believe you can view a CSV in github on a browser, you need to download it to view it. which means that it makes the list (to a certain degree) unusable for a mobile viewer
- I personally login to this account via tor only (for reasons I wont go into as they are off-topic) and if the file format is changed to CSV, I don't think that github offers a way to update a CSV in a repo behind Tor, right? (I know about TailsOS but something I rather avoid setting up just for a single repo)

I personally think that leaving it on plaintext is best but I also don't know if you see this repo as something that mobile users should be able to interact with easily and should be modifiable behind Tor.

**Comment by Peter-Easton** [comment]
Sure, that's perfectly understandable that you and others will need to protect your privacy. I'll see if what I might be able to do in the near future would be to write a macro or a script to put things in the correct order.

**Comment by Peter-Easton** [comment]
So, some things have changed a bit... https://github.com/Peter-Easton/GrapheneOS-Knowledge/commit/f1a5b14937807ed71d24f24de9460f5afc3a7c07#diff-c4752fc4db9ec2729afc7bd5b12da14683c27cfec700ee99e7bb9b16db1f1fc5

After Play Services Sandboxing has been implemented, it's now easier to enumerate what apps don't work on GrapheneOS, rather than which ones do.
